# Generated by Django 4.1.5 on 2023-01-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=25)),
                ('citizenship', models.CharField(max_length=200)),
                ('foot', models.CharField(max_length=30)),
                ('player_agent', models.CharField(max_length=200)),
                ('agent_link', models.URLField(max_length=600)),
                ('current_club', models.CharField(max_length=50)),
                ('joined', models.CharField(max_length=50)),
                ('contract_expires', models.CharField(max_length=50)),
                ('outfitter', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('current_value', models.CharField(max_length=30)),
                ('max_value', models.CharField(max_length=100)),
                ('max_value_date', models.CharField(max_length=50)),
                ('last_contract_extension', models.CharField(max_length=50)),
                ('league_name', models.CharField(max_length=50)),
                ('on_loan', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='link',
            field=models.URLField(max_length=600, unique=True),
        ),
    ]
