# Generated by Django 4.1.5 on 2023-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_basicplayer_alter_player_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicplayer',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
